remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
show_downloads: false
google_analytics: G-JKZ8XL30H6
title: Berk Selvi
description: Web developer studying CS in Turkey.