remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Hacker theme
description: Hacker is a theme for GitHub Pages.
show_downloads: false
google_analytics: G-JKZ8XL30H6