baseURL = 'https://berkselvi.dev'
languageCode = 'en-us'
defaultContentLanguage = 'en'
theme = "terminal"
pagination.pagerSize = 10
googleAnalytics = 'G-W0L24EMSQ5'

[markup.goldmark.renderer]
  unsafe = true

[params]
  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "green"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2

  # show selector to switch language
  showLanguageSelector = true

  # set theme to full screen width
  fullWidthTheme = false

  # center theme with default width
  centerTheme = true

  # if your resource directory contains an image called `cover.(jpg|png|webp)`,
  # then the file will be used as a cover automatically.
  # With this option you don't have to put the `cover` param in a front-matter.
  autoCover = true

  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  showLastUpdated = false

  # set a custom favicon (default is a `themeColor` square)
  favicon = "/icon/favicon.ico"

  # Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
  # updatedDatePrefix = "Updated"

  # set all headings to their default size (depending on browser settings)
  # oneHeadingSize = true # default

  # whether to show a page's estimated reading time
  readingTime = true

  # whether to show a table of contents
  # can be overridden in a page's front-matter
  # Toc = false # default

  # set title for the table of contents
  # can be overridden in a page's front-matter
  # TocTitle = "Table of Contents" # default

[params.twitter]
  # set Twitter handles for Twitter cards
  # see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
  # do not include @
  creator = "berkslv"
  site = ""

[languages]
  [languages.en]
    disabled = false
    languageName = "english"
    languageCode = 'en-US'
    contentDir = 'content/english'
    weight = 1
    title = "Berk Selvi | Software Developer"
    subtitle = ".NET Developer, blogger and builder."
    owner = ""
    keywords = ""
    copyright = "Made by Berk Selvi. <br> This site is <a href='https://github.com/berkslv/berkselvi.dev' target='_blank'>open source</a>"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"
    translations = "For turkish version;"

    [languages.en.params.logo]
      logoText = "Berk Selvi"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "home"
        name = "home"
        url = "/"
        weight = 1

  [languages.tr]
    disabled = false
    languageName = "türkçe"
    languageCode = 'tr-TR'
    contentDir = 'content/turkish'
    weight = 2
    title = "Berk Selvi | Software Developer"
    subtitle = ".NET Developer, blogger and builder."
    owner = ""
    keywords = ""
    copyright = "Made by Berk Selvi. <br> Bu websitesi <a href='https://github.com/berkslv/berkselvi.dev' target='_blank'>open source</a> olarak yayınlanmıştır."
    menuMore = "Daha fazla göster"
    readMore = "Devamını oku"
    readOtherPosts = "Diğer yazıları oku"
    newerPosts = "Yeni yazılar"
    olderPosts = "Eski yazılar"
    missingContentMessage = "Sayfa bulunamadı..."
    missingBackButtonLabel = "Ana sayfaya dön"
    translations = "İngilizce versiyonu için;"

    [languages.tr.params.logo]
      logoText = "Berk Selvi"
      logoHomeLink = "/"

    [languages.tr.menu]
      [[languages.tr.menu.main]]
        identifier = "home"
        name = "ana sayfa"
        url = "/tr"
        weight = 1

